services:

  piaware:
    image: mikenye/piaware
    restart: unless-stopped
    devices:
      - /dev/bus/usb:/dev/bus/usb
    ports:
      - 8090:80
    environment:
      - LAT=${LAT}
      - LONG=${LONG}
      - FEEDER_ID=${FEEDER_ID}
      - RECEIVER_TYPE=rtlsdr

  zigbee2mqtt:
    image: koenkk/zigbee2mqtt
    restart: unless-stopped
    devices:
      - /dev/serial/by-id/usb-Silicon_Labs_slae.sh_cc2652rb_stick_-_slaesh_s_iot_stuff_00_12_4B_00_25_9B_C1_B2-if00-port0:/dev/ttyUSB0
    ports:
      - "8083:8080"
    volumes:
      - /media/cluster/zigbee2mqtt/:/app/data
    environment:
      - DEBUG=zigbee-herdsman*
    healthcheck:
      test: "wget --no-verbose --tries=1 --spider http://127.0.0.1:8080 || exit 1"
      start_period: 30s
      interval: 30s
      timeout: 5s
      retries: 5

  govee2mqtt:
    image: ghcr.io/wez/govee2mqtt:latest
    restart: unless-stopped
    env_file:
      - .env
    network_mode: host
