version: '3.8'
services:

  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto
    restart: unless-stopped
    ports:
      - 1883:1883
    volumes:
      - /home/pi/volumes/mosquitto/data:/mosquitto/data
      - /home/pi/volumes/mosquitto/log:/mosquitto/log
      - /home/pi/services/mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf

