version: '3.8'
services:

  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto
    restart: unless-stopped
    ports:
      - 1883:1883
    volumes:
      - /media/cluster/config/mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - /media/cluster/data/mosquitto/:/mosquitto/data
      - /var/log:/mosquitto/log

  node-exporter:
    container_name: node-exporter
    image: prom/node-exporter
    restart: unless-stopped
    ports:
      - 9100:9100
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)'

  prometheus:
    container_name: prometheus
    image: prom/prometheus
    restart: unless-stopped
    ports:
      - 9090:9090
    volumes:
      - /media/cluster/config/prometheus:/etc/prometheus
      - /media/cluster/data/prometheus/:/prometheus

  grafana:
    container_name: grafana
    image: grafana/grafana
    user: "0"
    restart: unless-stopped
    ports:
      - 3000:3000
    env_file:
      - /media/cluster/config/grafana/grafana.env
    volumes:
      - /media/cluster/data/grafana/:/var/lib/grafana
      - /var/log/grafana:/var/log/grafana

  homeassistant:
    container_name: homeassistant
    image: homeassistant/raspberrypi4-homeassistant:stable
    volumes:
      - /media/cluster/data/homeassistant:/config
    restart: unless-stopped
    network_mode: host

  timemachine:
    # NOTE: Assumes user `timemachine` already exists on the system and is the owner of `/media/tm`
    container_name: timemachine
    image: mbentley/timemachine:smb-armv7l
    restart: unless-stopped
    network_mode: host
    environment:
      - TM_UID=111
      - TM_GID=115
    volumes:
      - /media/tm:/opt/timemachine
