version: '3.8'
services:

  mosquitto:
    image: eclipse-mosquitto
    networks:
      - homenet
    restart: unless-stopped
    ports:
      - 1883:1883
    volumes:
      - /media/cluster/config/mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - /media/cluster/data/mosquitto/:/mosquitto/data
      - /var/log:/mosquitto/log

  node-exporter:
    image: prom/node-exporter
    networks:
      - homenet
    restart: unless-stopped
    ports:
      - 9100:9100
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)'

  prometheus:
    image: prom/prometheus
    networks:
      - homenet
    restart: unless-stopped
    ports:
      - 9090:9090
    volumes:
      - /media/cluster/config/prometheus:/etc/prometheus
      - /media/cluster/data/prometheus/:/prometheus

  grafana:
    image: grafana/grafana
    networks:
      - homenet
    user: "0"
    restart: unless-stopped
    ports:
      - 3000:3000
    env_file:
      - /media/cluster/config/grafana/grafana.env
    volumes:
      - /media/cluster/data/grafana/:/var/lib/grafana
      - /var/log/grafana:/var/log/grafana

  homeassistant:
    image: homeassistant/raspberrypi4-homeassistant:stable
    networks:
      - homenet
    restart: unless-stopped
    ports:
      - 8123:8123  # Note some auto-discovery might not work
    volumes:
      - /media/cluster/data/homeassistant:/config

  timemachine:
    # NOTE: Assumes user `timemachine` already exists on the system and is the owner of `/media/tm`
    image: mbentley/timemachine:smb-armv7l
    networks:
      - homenet
    restart: unless-stopped
    ports:
      - 137:137/udp
      - 138:138/udp
      - 139:139
      - 445:445
    environment:
      - TM_UID=111
      - TM_GID=115
    volumes:
      - /media/tm:/opt/timemachine

networks:
    homenet:
        driver: overlay
        attachable: true
