version: "3.8"

services:

  mosquitto:
    image: eclipse-mosquitto
    ports:
      - "1883:1883"
    volumes:
      - /media/cluster/mosquitto/:/mosquitto/config/
      - /media/cluster/mosquitto/:/mosquitto/data
      - /var/log:/mosquitto/log

  zigbee2mqtt:
    image: koenkk/zigbee2mqtt
    ports: 
      - "8083:8080"
    volumes:
      - /media/cluster/zigbee2mqtt/:/app/data
    environment:
      - DEBUG=zigbee-herdsman*

  node-red:
    image: nodered/node-red:latest
    ports:
      - "1880:1880"
    environment:
      - Europe/Sweden
    volumes:
      - /media/cluster/node-red:/data
    networks:
      - default
      - proxy_default
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.nodered-secure.rule=Host(`nodered.humby.co.za`)&&PathPrefix(`/webhook`)"
        - "traefik.http.routers.nodered-secure.entrypoints=websecure"
        - "traefik.http.routers.nodered-insecure.rule=Host(`nodered.humby.co.za`)&&PathPrefix(`/spotify/albumart`)"
        - "traefik.http.routers.nodered-insecure.entrypoints=web"
        - "traefik.http.routers.nodered-secure.tls.certresolver=mytlschallenge"
        - "traefik.http.services.nodered.loadbalancer.server.port=1880"

  homeassistant:
    image: homeassistant/home-assistant:stable
    ports:
      - "8123:8123"  # Note some auto-discovery might not work
      - "5353:5353/udp"  # Required for Apple HomeKit
      - "51827:51827"  # Apple HomeKit
    volumes:
      - /media/cluster/homeassistant:/config
    networks:
      - default
      - proxy_default
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.homeassistant-secure.rule=Host(`home.humby.co.za`)"
        - "traefik.http.routers.homeassistant-secure.entrypoints=websecure"
        - "traefik.http.routers.homeassistant-secure.tls.certresolver=mytlschallenge"
        - "traefik.http.services.homeassistant.loadbalancer.server.port=8123"

  tasmoadmin:
    image: raymondmm/tasmoadmin
    ports:
      - "8082:80"
    volumes:
      - /media/cluster/tasmoadmin/:/data

  esphome:
    image: esphome/esphome
    ports:
      - "6052:6052"
    volumes:
      - /media/cluster/esphome/:/config
    environment:
      - ESPHOME_DASHBOARD_USE_PING=true

  shlink:
    image: shlinkio/shlink:stable
    ports:
      - "8084:8080"
    volumes:
      - /media/cluster/shlink/shlink.sqlite:/etc/shlink/data/database.sqlite
    environment:
      - DEFAULT_DOMAIN=dhum.by
      - IS_HTTPS_ENABLED=true
      - DEFAULT_SHORT_CODES_LENGTH=4
      - DEFAULT_BASE_URL_REDIRECT=http://dalehumby.com
    networks:
      - proxy_default
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.shlink-secure.rule=Host(`dhum.by`)"
        - "traefik.http.routers.shlink-secure.entrypoints=websecure"
        - "traefik.http.routers.shlink-secure.tls.certresolver=mytlschallenge"
        - "traefik.http.services.shlink.loadbalancer.server.port=8080"  # containers internal port

  rhasspy:
    image: rhasspy/rhasspy:latest
    ports:
        - "12101:12101"
    volumes:
        - /media/cluster/rhasspy/:/profiles
        - /etc/localtime:/etc/localtime:ro
    deploy:
      placement:
        constraints:
          - "node.hostname==homedell"
    command:
      - --user-profiles=/profiles
      - --profile=en

  mimic3:
    image: mycroftai/mimic3
    ports:
      - 59125:59125
    volumes:
      - /media/cluster/mimic3:/home/mimic3/.local/share/mycroft/mimic3
    deploy:
      placement:
        constraints:
          - "node.hostname==homedell"
    command:
      - --default-voice=en_US/ljspeech_low
      - --noise-w=0.8
      - --noise-scale=0.667
      - --length-scale=1

  openwakeword:
    image: dalehumby/openwakeword-rhasspy
    ports:
      - "12202:12202/udp"
    volumes:
      - /media/cluster/openwakeword:/config

networks:
  default: {}
  proxy_default:
    external: true

