version: "3.8"

services:

  mosquitto:
    image: eclipse-mosquitto
    ports:
      - "1883:1883"
    volumes:
      - /media/cluster/mosquitto/:/mosquitto/config/
      - /media/cluster/mosquitto/:/mosquitto/data
      - /var/log:/mosquitto/log
    deploy:
      labels:
        - "traefik.enable=false"

  node-red:
    image: nodered/node-red:latest
    ports:
      - "1880:1880"
    environment:
      - TZ=Europe/Stockholm
    volumes:
      - /media/cluster/node-red:/data
    networks:
      - default
      - proxy_default
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.nodered-secure.rule=Host(`nodered.humby.co.za`) && PathPrefix(`/webhook`)"
        - "traefik.http.routers.nodered-secure.entrypoints=websecure"
        - "traefik.http.routers.nodered-secure.tls.certresolver=mytlschallenge"
        - "traefik.http.routers.nodered-secure.service=nodered"
        - "traefik.http.routers.nodered-insecure.rule=Host(`nodered.humby.co.za`) && PathPrefix(`/spotify/albumart`)"
        - "traefik.http.routers.nodered-insecure.entrypoints=web"
        - "traefik.http.routers.nodered-insecure.service=nodered"
        - "traefik.http.services.nodered.loadbalancer.server.port=1880"

  homeassistant:
    image: homeassistant/home-assistant:stable
    ports:
      - "8123:8123"
      # Apple HomeKit
      - mode: host
        protocol: udp
        published: 5353
        target: 5353
      - mode: host
        protocol: tcp
        published: 21063
        target: 21063
      # Shelly CoIoT https://www.home-assistant.io/integrations/shelly/#shelly-device-configuration-generation-1
      - mode: host
        protocol: udp
        published: 5683
        target: 5683
    volumes:
      - /media/cluster/homeassistant:/config
    networks:
      - default
      - proxy_default
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.homeassistant-secure.rule=Host(`home.humby.co.za`)"
        - "traefik.http.routers.homeassistant-secure.entrypoints=websecure"
        - "traefik.http.routers.homeassistant-secure.tls.certresolver=mytlschallenge"
        - "traefik.http.routers.homeassistant-secure.service=homeassistant"
        - "traefik.http.services.homeassistant.loadbalancer.server.port=8123"

  esphome:
    image: esphome/esphome
    ports:
      - "6052:6052"
    volumes:
      - /media/cluster/esphome/:/config
    environment:
      - ESPHOME_DASHBOARD_USE_PING=true
    deploy:
      labels:
        - "traefik.enable=false"

  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    ports:
      - "8081:3000"
    environment:
      - HOMEPAGE_ALLOWED_HOSTS=10.0.0.10:8081
    volumes:
      - /media/cluster/homepage:/app/config
    deploy:
      labels:
        - "traefik.enable=false"

  syslog:
    image: lscr.io/linuxserver/syslog-ng:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Stockholm
    volumes:
      - /media/cluster/syslog:/config
      - /media/cluster/syslog/log:/var/log
    ports:
      - 514:5514/udp
      - 601:6601/tcp
    deploy:
      labels:
        - "traefik.enable=false"

  convertx:
    image: ghcr.io/c4illin/convertx
    ports:
      - "8082:3000"
    environment:
      - HTTP_ALLOWED=true
      - ALLOW_UNAUTHENTICATED=true
    volumes:
      - /media/cluster/convertx:/app/data
    deploy:
      labels:
        - "traefik.enable=false"

networks:
  default: {}
  proxy_default:
    external: true
