---
- name: Add required folders, config files etc for all my services
  hosts: localhost
  connection: local
  become: yes
  become_user: pi
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:

    # Mosquitto MQTT Broker
    - name: Create Mosquitto data dir
      file:
        path: /media/cluster/data/mosquitto
        state: directory

    - name: Create Mosquitto config dir
      file:
        path: /media/cluster/config/mosquitto
        state: directory

    - name: Copy Mosquitto config file
      copy:
        src: ./mosquitto/mosquitto.conf
        dest: /media/cluster/config/mosquitto/mosquitto.conf

    - name: Copy Mosquitto password file
      copy:
        src: ./mosquitto/passwd
        dest: /media/cluster/config/mosquitto/passwd

    # Prometheus
    - name: Create Prometheus data dir
      # See https://stackoverflow.com/questions/50009065/how-to-persist-data-in-prometheus-running-in-a-docker-container
      file:
        path: /media/cluster/data/prometheus
        state: directory
        owner: nobody

    - name: Create Prometheus config dir
      file:
        path: /media/cluster/config/prometheus
        state: directory

    - name: Copy Prometheus config file
      copy:
        src: ./prometheus/prometheus.yml
        dest: /media/cluster/config/prometheus/prometheus.yml

    # Grafana
    - name: Create Grafana data dir
      file:
        path: /media/cluster/data/grafana
        state: directory

    - name: Create Grafana config dir
      file:
        path: /media/cluster/config/grafana
        state: directory

    - name: Copy Grafana env variables file
      copy:
        src: ./grafana/grafana.env
        dest: /media/cluster/config/grafana/grafana.env

    - name: Create Grafana log dir
      file:
        path: /var/log/grafana
        state: directory

    # Node Red
    - name: Create Node Red data dir
      file:
        path: /media/cluster/data/node-red
        state: directory

    # Home Assistant
    - name: Checkout Home Assistant configs
      git:
        repo: git@github.com:dalehumby/homeassistant-config.git
        dest: /media/cluster/data/homeassistant

    # Owntracks recorder
    - name: Create Owntracks Recorder data dir
      file:
        path: /media/cluster/data/owntracks
        state: directory

    # Gluster FS
    - name: Create Gluster log dir
      file:
        path: /var/log/glusterfs
        state: directory
